[2024-07-17T09:12:00.341+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-17T09:12:00.381+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: parse_data_dag.parse_data manual__2024-07-17T09:11:56.486225+00:00 [queued]>
[2024-07-17T09:12:00.392+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: parse_data_dag.parse_data manual__2024-07-17T09:11:56.486225+00:00 [queued]>
[2024-07-17T09:12:00.393+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-17T09:12:00.411+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): parse_data> on 2024-07-17 09:11:56.486225+00:00
[2024-07-17T09:12:00.428+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=99) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-17T09:12:00.435+0000] {standard_task_runner.py:64} INFO - Started process 102 to run task
[2024-07-17T09:12:00.428+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'parse_data_dag', 'parse_data', 'manual__2024-07-17T09:11:56.486225+00:00', '--job-id', '47', '--raw', '--subdir', 'DAGS_FOLDER/parsing_dag.py', '--cfg-path', '/tmp/tmpszuw5oa1']
[2024-07-17T09:12:00.436+0000] {standard_task_runner.py:91} INFO - Job 47: Subtask parse_data
[2024-07-17T09:12:00.507+0000] {task_command.py:426} INFO - Running <TaskInstance: parse_data_dag.parse_data manual__2024-07-17T09:11:56.486225+00:00 [running]> on host 1254a1bc6f0b
[2024-07-17T09:12:00.636+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='parse_data_dag' AIRFLOW_CTX_TASK_ID='parse_data' AIRFLOW_CTX_EXECUTION_DATE='2024-07-17T09:11:56.486225+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-17T09:11:56.486225+00:00'
[2024-07-17T09:12:00.651+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-17T09:12:21.555+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-17T09:12:21.556+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/parsing_dag.py", line 127, in parse_data
    result_in_city = process_table(driver, options_in_city)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/parsing_dag.py", line 50, in process_table
    buy_rate_button.click()
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webelement.py", line 94, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webelement.py", line 395, in _execute
    return self._parent.execute(command, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 354, in execute
    self.error_handler.check_response(response)
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
  (Session info: chrome-headless-shell=124.0.6367.78)
Stacktrace:
#0 0x556ed4cc1ca7 <unknown>
#1 0x556ed49989aa <unknown>
#2 0x556ed49df590 <unknown>
#3 0x556ed49d4f1a <unknown>
#4 0x556ed49fff86 <unknown>
#5 0x556ed49d4912 <unknown>
#6 0x556ed4a00132 <unknown>
#7 0x556ed4a1cf16 <unknown>
#8 0x556ed49ffce7 <unknown>
#9 0x556ed49d26b1 <unknown>
#10 0x556ed49d34c6 <unknown>
#11 0x556ed4c8f55a <unknown>
#12 0x556ed4c928ea <unknown>
#13 0x556ed4c92393 <unknown>
#14 0x556ed4c92d79 <unknown>
#15 0x556ed4c7fb2f <unknown>
#16 0x556ed4c93134 <unknown>
#17 0x556ed4c685aa <unknown>
#18 0x556ed4cb2459 <unknown>
#19 0x556ed4cb2646 <unknown>
#20 0x556ed4cc1193 <unknown>
#21 0x7f0ff3ea2134 <unknown>

[2024-07-17T09:12:21.576+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=parse_data_dag, task_id=parse_data, run_id=manual__2024-07-17T09:11:56.486225+00:00, execution_date=20240717T091156, start_date=20240717T091200, end_date=20240717T091221
[2024-07-17T09:12:21.599+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 47 for task parse_data (Message: element not interactable
  (Session info: chrome-headless-shell=124.0.6367.78)
Stacktrace:
#0 0x556ed4cc1ca7 <unknown>
#1 0x556ed49989aa <unknown>
#2 0x556ed49df590 <unknown>
#3 0x556ed49d4f1a <unknown>
#4 0x556ed49fff86 <unknown>
#5 0x556ed49d4912 <unknown>
#6 0x556ed4a00132 <unknown>
#7 0x556ed4a1cf16 <unknown>
#8 0x556ed49ffce7 <unknown>
#9 0x556ed49d26b1 <unknown>
#10 0x556ed49d34c6 <unknown>
#11 0x556ed4c8f55a <unknown>
#12 0x556ed4c928ea <unknown>
#13 0x556ed4c92393 <unknown>
#14 0x556ed4c92d79 <unknown>
#15 0x556ed4c7fb2f <unknown>
#16 0x556ed4c93134 <unknown>
#17 0x556ed4c685aa <unknown>
#18 0x556ed4cb2459 <unknown>
#19 0x556ed4cb2646 <unknown>
#20 0x556ed4cc1193 <unknown>
#21 0x7f0ff3ea2134 <unknown>
; 102)
[2024-07-17T09:12:21.649+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-07-17T09:12:21.667+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-17T09:12:21.669+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
